# Setting up the environment

## Importing libraries

In [ ]:
import pandas as pd
import numpy as np

## Contructing dataframe of features and activations

In [ ]:
# Features
f1 = np.array([2, 1, 5, 6, 7])
f2 = np.array([3, 1, 4, 1, 1])

# Activations
z1 = np.array([7, 2, 1, 7, 3])
z2 = np.array([5, 3, 2, 5, 3])

# Dataframe
df = pd.DataFrame(data={'f1': f1, 'f2': f2, 'z1': z1, 'z2': z2})
df

   f1  f2  z1  z2
0   2   3   7   5
1   1   1   2   3
2   5   4   1   2
3   6   1   7   5
4   7   1   3   3

# Batch Normalisation

## Step 1: Normalisation

In [ ]:
epsilon = 1e-4
dfb = df.copy()

# Calculating mean and standard deviation
m1 = dfb['z1'].mean()
s1 = dfb['z1'].std()
m2 = dfb['z2'].mean()
s2 = dfb['z2'].std()

# Normalisation
dfb['z1'] = (dfb['z1']-m1)/(s1+epsilon)     # To avoid zero division error
dfb['z2'] = (dfb['z2']-m2)/(s2+epsilon)
dfb

   f1  f2        z1        z2
0   2   3  1.060623  1.043421
1   1   1 -0.707082 -0.447180
2   5   4 -1.060623 -1.192481
3   6   1  1.060623  1.043421
4   7   1 -0.353541 -0.447180

## Step 2: Scaling and shifting

In [ ]:
# Some value of gamma and beta
gamma1, beta1 = 0.8, 0.5
gamma2, beta2 = 0.7, 0.4

# Scaling and shifting
dfb['z1'] = gamma1*dfb['z1'] + beta1
dfb['z2'] = gamma2*dfb['z2'] + beta2
dfb

   f1  f2        z1        z2
0   2   3  1.348498  1.130394
1   1   1 -0.065665  0.086974
2   5   4 -0.348498 -0.434736
3   6   1  1.348498  1.130394
4   7   1  0.217167  0.086974

## **Step 3: Applying activation function**. We consider the activation function to be relu.
$$RelU = max(0, z)$$

In [ ]:
def relu(z):
    # Using np.maximum for efficient element-wise ReLU
    return np.maximum(0, z)

# Calculating activations
a1 = relu(dfb['z1'])
a2 = relu(dfb['z2'])

dfb['a1'] = a1
dfb['a2'] = a2
dfb

   f1  f2        z1        z2        a1        a2
0   2   3  1.348498  1.130394  1.348498  1.130394
1   1   1 -0.065665  0.086974  0.000000  0.086974
2   5   4 -0.348498 -0.434736  0.000000  0.000000
3   6   1  1.348498  1.130394  1.348498  1.130394
4   7   1  0.217167  0.086974  0.217167  0.086974

# Layer Normalisation

## Step 1: Normalisation

In [ ]:
dfl = df.copy()

for i in range(len(dfl)):
    # Ensure the columns are of float type before assignment
    dfl['z1'] = dfl['z1'].astype(float)
    dfl['z2'] = dfl['z2'].astype(float)

    # Calculating mean and variance
    data = np.array(dfl.loc[i])[-2:]
    mean = data.mean()
    std = data.std()

    # Normalisation
    data = (data-mean)/(std+epsilon)    # To avoid zero division error
    dfl.iloc[i, -2:] = data

dfl

   f1  f2      z1      z2
0   2   3  0.9999 -0.9999
1   1   1 -0.9998  0.9998
2   5   4 -0.9998  0.9998
3   6   1  0.9999 -0.9999
4   7   1  0.0000  0.0000

## Step 2: Scaling and shifting

In [ ]:
# Some value of gamma and beta
gamma1, beta1 = 0.8, 0.5
gamma2, beta2 = 0.7, 0.4

# Scaling and shifting
dfl['z1'] = gamma1*dfl['z1'] + beta1
dfl['z2'] = gamma2*dfl['z2'] + beta2
dfl

   f1  f2       z1       z2
0   2   3  1.29992 -0.29993
1   1   1 -0.29984  1.09986
2   5   4 -0.29984  1.09986
3   6   1  1.29992 -0.29993
4   7   1  0.50000  0.40000

## **Step 3: Applying activation function**. We consider the activation function to be relu.
$$RelU = max(0, z)$$

In [ ]:
def relu(z):
    # Using np.maximum for efficient element-wise ReLU
    return np.maximum(0, z)

# Calculating activations
a1 = relu(dfl['z1'])
a2 = relu(dfl['z2'])

dfl['a1'] = a1
dfl['a2'] = a2
dfl

   f1  f2       z1       z2       a1       a2
0   2   3  1.29992 -0.29993  1.29992  0.00000
1   1   1 -0.29984  1.09986  0.00000  1.09986
2   5   4 -0.29984  1.09986  0.00000  1.09986
3   6   1  1.29992 -0.29993  1.29992  0.00000
4   7   1  0.50000  0.40000  0.50000  0.40000